### ISSUE TITLE
Make help document

### ISSUE THREAD

**Issue by alosdiallo** [alosdiallo/HiC_Network_Viz_tool#10]
Use the pdf that Ricardo made as the help page.  Work with Ricardo to get an updated pdf.

**Comment by KHBHH** [comment]
This should be done at the end.

**Comment by KHBHH** [comment]
I added a modal that whenever the user uploads the data, a message is shown to make sure that data exists in right indexes of columns, (whether it does or not), and then proceed to the next step. But I hope the user does not think that there is something wrong whenever that message is shown, what do you think?

**Comment by alosdiallo** [comment]
I think I would have to take a look for myself and check.

**Comment by rnr-HMS** [comment]
Please let me know when the app is up-to-date for me to redo this, thanks!

**Comment by alosdiallo** [comment]
I think tomorrow.  I know Karni was going release it soon.  I will ask her.  Thanks!
