### ISSUE TITLE
The interactive tutorial button is covered up by the reload app button

### ISSUE THREAD

**Issue by alosdiallo** [alosdiallo/HiC_Network_Viz_tool#12]
The interactive tutorial button is covered up by the reload app button

**Comment by KHBHH** [comment]
task: try to use divs inside tables: 

https://css-tricks.com/using-divs-inside-tables/

**Comment by KHBHH** [comment]
This si done. I have used the CSS trick (divs inside tables), so I have included a seperate html file to do this.

**Comment by alosdiallo** [comment]
Okay cool I will check in the morning.

**Comment by alosdiallo** [comment]
fixed
