### ISSUE TITLE
Download XGMML does not download the correct file

### ISSUE THREAD

**Issue by alosdiallo** [alosdiallo/HiC_Network_Viz_tool#13]
When I download the XGMML file on the QA site it does not download the proper file.  It downloads some html.

**Comment by KHBHH** [comment]
I will look at it.

**Comment by KHBHH** [comment]
This makes sence, because the whole function (downloadhandler for xgmml) does not exist in my code, which is weird, maybe I have removed it by mistake! 

I included it, it works locally, I will test it tomorrow on shinyapps.io and will update you with the final results.

**Comment by alosdiallo** [comment]
Yeah this came about because I had a meeting with Christophe where we looked over the app.  It didn't look too good....  Likely it was just a mistake.  Please try to fix it.

**Comment by KHBHH** [comment]
This is fixed, you can check it here https://hmsimmunodept.shinyapps.io/DNARchitect_qa/ .

**Comment by alosdiallo** [comment]
Looks good thanks
