### ISSUE TITLE
create network using Visnetwork package

### ISSUE THREAD

**Issue by KHBHH** [alosdiallo/HiC_Network_Viz_tool#16]
Regarding the network, we have the following:
- interactive network
- Having the option to edit the network (delete node/add node/edge)
- save the network in html file (so that when it is saved as html file, it will remain interactive)

I will deploy the above changes to the qa version later in the day.

**Comment by alosdiallo** [comment]
You should not have the file saved as an HTML file.  You want to save an xgmml and svg file.  If this is not easy to do we can discuss it.

**Comment by KHBHH** [comment]
I added the layout needed to make the network stable. Now it is shown with arrows. I will apply the changes to the qa version later in the day today.

**Comment by alosdiallo** [comment]
done
