### ISSUE TITLE
Load sample data

### ISSUE THREAD

**Issue by KHBHH** [alosdiallo/HiC_Network_Viz_tool#17]
This is done, I will apply the changes to the qa version later in the day.

What I want to make sure here is that whenever the user runs the app, the chosen type of file by default is HiC, and then the user can load data. If the user chooses ATAC and then decides to load sample data, should there be different types of data to load other than the ones which were there while HiC was chosen? Or no matter what the user chooses the sample data to load should be fixed?

**Comment by alosdiallo** [comment]
How do we see this?

**Comment by alosdiallo** [comment]
closing
