### ISSUE TITLE
Download plot as pdf

### ISSUE THREAD

**Issue by alosdiallo** [alosdiallo/HiC_Network_Viz_tool#18]
Download the plot as a pdf

**Comment by KHBHH** [comment]
This was regarding the network, done.

**Comment by KHBHH** [comment]
I just figured out that in both chrome & edge the network downloads as .htm, while in explorer it reruns the app. Locally it works, but when I deployed it, it started behave strange like this. I will look at it tomorrow.

This was working before, so I should be able to fix it.

**Comment by KHBHH** [comment]
working on this

**Comment by KHBHH** [comment]
fixed.

**Comment by alosdiallo** [comment]
Great.
