### ISSUE TITLE
Header check does nothing

### ISSUE THREAD

**Issue by alosdiallo** [alosdiallo/HiC_Network_Viz_tool#2]
The site should not require a header.  Ask the user if they have a header or not.  If not don't require a header.

**Comment by KHBHH** [comment]
Now the site does not require a header. A checkbox input asks the user if the file contains header or not. 

Task to be done: 
1. A message should be included to infrom the user that information should be in specific indexes of columns, such as: chrom1 : will be in 1st column
                                               start1    : 2nd column
                                               end1      :3rd column
                                               chrom2  :4th column
                                               start2     :5th column
                                               end2       :6th column
                                               score       :7th column
                                               samplenumber: 8th column
2. I should consider testing with ATAC data. (bedheader and bedgraphHeaders)

**Comment by alosdiallo** [comment]
I will check

**Comment by KHBHH** [comment]
Headercheck only asks the user of the data that he/she uplaoded contains headers or not. It doesn't do anything else.

**Comment by alosdiallo** [comment]
fixed
