### ISSUE TITLE
Have 1 button to download all plots on the left

### ISSUE THREAD

**Issue by alosdiallo** [alosdiallo/HiC_Network_Viz_tool#22]
Have 1 button to download all plots on the left for both pdf and svg

**Comment by KHBHH** [comment]
For PDF plot id done.

But for SVG, I used downloandhandler as I did for pdf, but it results in downlaoding only 1 plot when I press the button when I run 2 plots/more. I suppose svg should not be done with downloandhandler if I want to download multiple svg files. What do you think? I am still searching for solution to this.

**Comment by KHBHH** [comment]
Regarding svg download, after doing some research it seems it is not simple to download multiple svg files without having to zip them up first. I found a dicsussion about this but for csv files, I am trying to figure out if I can do the same for svg files (plots).

**Comment by alosdiallo** [comment]
Zip files are totally fine.

**Comment by KHBHH** [comment]
downloading the plots in a zipped file is done. I will rename the folder name tomorrow. Right now it is (zippedfolders).

PLease check and tell me if it is okay.

**Comment by alosdiallo** [comment]
Great I will check tomorrow.
