### ISSUE TITLE
Datasets other than K562 are broken

### ISSUE THREAD

**Issue by alosdiallo** [alosdiallo/HiC_Network_Viz_tool#24]
Datasets other than K562 are broken

**Comment by KHBHH** [comment]
what do you mean exactly here?

**Comment by alosdiallo** [comment]
When I tried to load the other sample datasets it did not work

**Comment by KHBHH** [comment]
Other than K562 there are 2 sample datasets: FOXP3 and hic_bedpe.

FOXP3 works with me when I try to load it. (but type of file chosen by default is HIC for now). Can you check please if that still does not work with you?

Regarding hic_bedpe, in the code I am reading from a text file which I included it in www directory. So if you do not have it, I think it's logical to see an error. At the mean time I wanted to ask do we have this file as a link on google drive? And are we going to use this file as sample data?

**Comment by KHBHH** [comment]
solved

**Comment by KHBHH** [comment]
I included the samples again, and when I deployed it, it read normally from the file. I did not feel any latency. Please can you check and confirm?

**Comment by alosdiallo** [comment]
I will look today.
