### ISSUE TITLE
Gene font size 

### ISSUE THREAD

**Issue by rnr-HMS** [alosdiallo/HiC_Network_Viz_tool#28]
Since we typically zoom out and include many genes in the bezier curve plots, is there a way to reduce the gene label font size?

**Comment by KHBHH** [comment]
I have reduced the scale by 0.2 now. I think it should be fine. Please let me know what you think.

**Comment by rnr-HMS** [comment]
Ramirez, Ricardo has shared a OneDrive for Business file with you. To view it, click the link below.


<https://hu-my.sharepoint.com/personal/ricardo_ramirez_hms_harvard_edu/Documents/Attachments/Screen%20Shot%202019-04-12%20at%202.53.36%20PM.png>
[https://r1.res.office365.com/owa/prem/images/dc-png_20.png]<https://hu-my.sharepoint.com/personal/ricardo_ramirez_hms_harvard_edu/Documents/Attachments/Screen%20Shot%202019-04-12%20at%202.53.36%20PM.png>

Screen Shot 2019-04-12 at 2.53.36 PM.png<https://hu-my.sharepoint.com/personal/ricardo_ramirez_hms_harvard_edu/Documents/Attachments/Screen%20Shot%202019-04-12%20at%202.53.36%20PM.png>




Hi Karni,

I think you can should set it at 0.1.

Thanks


Ricardo N. Ramirez, Ph.D.
Postdoctoral fellow in the Department of Immunology, Harvard Medical School, Boston, MA


________________________________

**Comment by rnr-HMS** [comment]
To view Screen Shot 2019-04-12 at 2.53.36 PM.png, sign in<https://hu-my.sharepoint.com/personal/ricardo_ramirez_hms_harvard_edu/_layouts/15/acceptinvite.aspx?invitation=%7BBE6A5B4C%2DE947%2D4F62%2DA6DE%2D7E72B98E0E65%7D&listId=1b105a95%2D3997%2D482a%2D8642%2De15eacf232e5&itemId=2395c8de%2Dbc10%2D4c64%2Da58a%2D2ef20509eea7> or create an account.

**Comment by alosdiallo** [comment]
Sorry, you don't have access.  Is what I get

**Comment by rnr-HMS** [comment]
I do have access. I just responded via email.

**Comment by KHBHH** [comment]
I scaled it, but smaller than this, the letters are not readable. Let me know if I need to change it again.

**Comment by rnr-HMS** [comment]
I think the font is good.
