### ISSUE TITLE
Accept any text in header

### ISSUE THREAD

**Issue by alosdiallo** [alosdiallo/HiC_Network_Viz_tool#3]
Right now the code looks for specific text.  What we should do is require info to be in specific columns and allow for any header.

**Comment by KHBHH** [comment]
Task to be done:

1. A message should be included to infrom the user that information should be in specific indexes of columns, such as: chrom1 : will be in 1st column
   start1    : 2nd column
   end1      :3rd column
   chrom2  :4th column
   start2     :5th column
   end2       :6th column
   score       :7th column
   samplenumber: 8th column
2. I should consider testing with ATAC data. (bedheader and bedgraphHeaders)

**Comment by KHBHH** [comment]
Done. Right now, the app accepts data with header/without/any text. 

The checkheader asks if the data contains header or not. If the user does not answer it correctly an error will occur later when the submit button is pressed to view the plots. Therefore, the user should know before uploading the data if it has headers or not.

This is what we discussed to happen, right?

**Comment by alosdiallo** [comment]
fixed
