### ISSUE TITLE
List the organism for the sample data

### ISSUE THREAD

**Issue by alosdiallo** [alosdiallo/HiC_Network_Viz_tool#32]
Right now when you load the sample data it does not list the type of organism.

**Comment by alosdiallo** [comment]
K562_NHEK_GM12878-loops
Organisms | Homo sapiens; Mus musculus

GSM1704495_GMPro_Cap_rep1_filt5
Homo sapiens

GSM1704494_JKProCap_Rep1_Filt5
Homo sapiens

**Comment by KHBHH** [comment]
This is done, please tell me if it is okay.

**Comment by KHBHH** [comment]
I was thinking as we have put the organism types near these data, maybe we should have the organisms on the other sample data too? because we have more than these 3 types of data.

**Comment by alosdiallo** [comment]
What I meant was in the about data tab to put the organism information there.

**Comment by KHBHH** [comment]
This is done, I added in the tab **About Sample Data**
