### ISSUE TITLE
Add to the site: Tcon_Immgen_3.bg   Treg_Immgen_3.bg

### ISSUE THREAD

**Issue by alosdiallo** [alosdiallo/HiC_Network_Viz_tool#33]
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE100738
I have the the files but will add.

**Comment by KHBHH** [comment]
Yes, I am waiting for the link so that I can add it (https://.....).

**Comment by alosdiallo** [comment]
https://storage.googleapis.com/gencode_ch_data/Sample_Data/datasets/Tcon_Immgen_3.bg
https://storage.googleapis.com/gencode_ch_data/Sample_Data/datasets/Treg_Immgen_3.bg

**Comment by KHBHH** [comment]
added the information to the site. They are named as
 ImmGen_T.Nve.Sp.ATAC.bg 
ImmGen_Treg.Sp.ATAC.bg

**Comment by alosdiallo** [comment]
They don't appear to be on the QA version.
