### ISSUE TITLE
Loading sample data does not display information about the dataset

### ISSUE THREAD

**Issue by alosdiallo** [alosdiallo/HiC_Network_Viz_tool#35]
Loading sample data does not display information about the dataset

**Comment by KHBHH** [comment]
Right now, instead of showing the information right away when I loaded the data, I added another tab (**About Sample Data**) and put all the informtaion there. What do you think? Would that work? (It was easier and faster for me to out it in that way)

**Comment by alosdiallo** [comment]
It is okay for now.  I will close this ticket.
