### ISSUE TITLE
If you fail to pick a color the app fails, if you then select colors it is nothing happens when you select submit perimeters

### ISSUE THREAD

**Issue by alosdiallo** [alosdiallo/HiC_Network_Viz_tool#40]
Production version
If you fail to pick a color the app fails, if you then select colors it is nothing happens when you select submit perimeters
![screen_shot](https://user-images.githubusercontent.com/3083525/58596597-b81ef600-8242-11e9-9957-76d1f0115d73.png)
.

**Comment by KHBHH** [comment]
This should be fixed now. (Refer to #41)
