### ISSUE TITLE
If you do not select colors the box should be red

### ISSUE THREAD

**Issue by alosdiallo** [alosdiallo/HiC_Network_Viz_tool#41]
If you do not select colors the box should be red indicating that this is missing

**Comment by KHBHH** [comment]
I am working on this. Apparently select input (multiple) does not support the feature of css trick, to include **required** in it. 
I have to write js/jquery code for it, I am looking into it.

**Comment by KHBHH** [comment]
As I understood from some research I did today that select multiple does not support the required feature, therefore I can not color it red if not selected.

Instead I added a requirement in shiny that submitbycoordaintes/by genes button will not work if color is not chosen. Now I will add a small pop up message to say this.

**Comment by KHBHH** [comment]
I added small message now, in case color is not selected it will show.

Please tell me if this is okay or if you have any suggestions.

**Comment by alosdiallo** [comment]
Put the notification next to the select parameters button and have it last for more than 5 seconds say 10 seconds. Have the color be more striking maybe bright yellow.

**Comment by KHBHH** [comment]
I used the feature **shinyalert**. Let me know if this works.

**Comment by alosdiallo** [comment]
Looks good
