### ISSUE TITLE
You can't load more than 1 dataset

### ISSUE THREAD

**Issue by alosdiallo** [alosdiallo/HiC_Network_Viz_tool#43]
You can't load more than 1 dataset.  If you try it crashes.

**Comment by rnr-HMS** [comment]
I tried to load HiC + ChIP-seq, HiC + ATAC, ChIP + ATAC, and it disconnected when trying to plot.

**Comment by alosdiallo** [comment]
This works

**Comment by KHBHH** [comment]
Tried HIC (K562 data)  with ChIP-seq(FoxP3..) data and I got the following.
![sc2](https://user-images.githubusercontent.com/39968446/58670152-58a61080-833e-11e9-8778-384619d4941f.png)
![sc1](https://user-images.githubusercontent.com/39968446/58670163-60fe4b80-833e-11e9-92cd-2c943b01ce11.png)
