### ISSUE TITLE
Include an option for choosing colors for the bezier curves

### ISSUE THREAD

**Issue by KHBHH** [alosdiallo/HiC_Network_Viz_tool#8]

**Comment by KHBHH** [comment]
This is done. 

But there is a bug that whenever I choose color for a second time and press 'Submit Parameters', it does not work. I am working on that.  (I will update the changes into the website shortly)

**Comment by KHBHH** [comment]
I am still not able to figure out this bug.

**Comment by alosdiallo** [comment]
Is this working now?

**Comment by KHBHH** [comment]
Yes, it is. I will update it to DNARchitect_qa version later in the day so that you can test.

**Comment by alosdiallo** [comment]
Resolving to close
